theme: jekyll-theme-minimal
title: Penn State IEEE Projects 2020
description: Materials from Penn State IEEE projects from Fall 2020 and Spring 2021

avatar: https://avatars.githubusercontent.com/u/82354684?s=200&v=4

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: psuieee
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: psuieee
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
